[tool.isort]
profile = "black"

[tool.pylint]
disable = [
    "C0103",  # invalid-name (module name doesn't conform to snake_case)
    "C0114",  # missing-module-docstring
    "C0116",  # missing-function-docstring
]
